import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const coinmarket = await fetch('https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?start=1&limit=30&sort=market_cap&cryptocurrency_type=all&tag=all', {
      headers: {
      'X-CMC_PRO_API_KEY': `${process.env.NEXT_PUBLIC_COINMARKETCAP_APIKEY}`,
      'Accept': 'application/json'
      },
      next: {
        revalidate: 60*60,
      }
  })
  .then(coinmarketRes => {
      return coinmarketRes.json();
  })
  .catch(err => {
      console.log("Error fetching data from Coinmarket with an error ", err)
  })

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
